export default [
  {
    name: "man-04gbgj2g0l7mv6qh.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "43",
  },
  {
    name: "man-0kyssvjtipnus0fb.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "7",
  },
  {
    name: "man-0pl4jsre170ri0a4.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "40",
  },
  {
    name: "man-0sli4h5pv23p1jvr.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "60",
  },
  {
    name: "man-0tnmmgtuz4xq0n6n.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "13",
  },
  {
    name: "man-0ve85paddmy9gzfa.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "36",
  },
  {
    name: "man-25rqiy017vjcdzqs.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "34",
  },
  {
    name: "man-2p0taqim998pv387.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "77",
  },
  {
    name: "man-2yswrpsv6n2nu0bx.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "96",
  },
  {
    name: "man-3n19bqwv7h9aywfk.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "58",
  },
  {
    name: "man-3sxmmsef2urtuw27.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "38",
  },
  {
    name: "man-3w902m6fafqy5b8u.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "29",
  },
  {
    name: "man-44qgnkwzfdfd1gmz.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "90",
  },
  {
    name: "man-4obvobj8hgittefy.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "98",
  },
  {
    name: "man-5kavj4hto7a3hwva.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "73",
  },
  {
    name: "man-69ii8bm6t2lb7qlu.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "2",
  },
  {
    name: "man-6j3wruaujf3d4tm6.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "21",
  },
  {
    name: "man-7n6uuccda4yqt5fx.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "32",
  },
  {
    name: "man-7x6e2oyxinmq9q58.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "18",
  },
  {
    name: "man-8rcggbej40fvqgl7.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "69",
  },
  {
    name: "man-9cdk8557vn8i9wfn.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "99",
  },
  {
    name: "man-9kztatr7vylzf2f0.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "56",
  },
  {
    name: "man-ao49z0a483s3yuvu.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "41",
  },
  {
    name: "man-b51rhtzamgb4ui9v.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "53",
  },
  {
    name: "man-b5d1namg7lvydf8k.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "83",
  },
  {
    name: "man-bc42kdpt8k04ye0y.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "65",
  },
  {
    name: "man-c3v84pf9ifmeshsb.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "62",
  },
  {
    name: "man-chi5gf8meie6yh5p.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "84",
  },
  {
    name: "man-ci768rpa2q9ex7ku.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "64",
  },
  {
    name: "man-cu4vcma18f5e84e9.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "49",
  },
  {
    name: "man-cwm150qi6v1kgutm.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "24",
  },
  {
    name: "man-d32ydb8k4gv3cunt.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "6",
  },
  {
    name: "man-dcub1rv59ihsnuzl.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "19",
  },
  {
    name: "man-evju2aw7fsi5q7rq.db.yandex.net",
    type: "ZOOKEEPER",
    health: "ALIVE",
  },
  {
    name: "man-fqcl8oi1yvkz2pgy.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "3",
  },
  {
    name: "man-frxlte7are2y3mi6.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "11",
  },
  {
    name: "man-g6xrfs3sr6y61ii0.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "9",
  },
  {
    name: "man-ggbzpt9ctgingkyi.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "5",
  },
  {
    name: "man-gggt5cj46s6v6g64.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "30",
  },
  {
    name: "man-h0qlqtkcio66rysp.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "25",
  },
  {
    name: "man-hj3t9j8s5zuatxkh.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "79",
  },
  {
    name: "man-hjkpwhqe0hlick7r.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "66",
  },
  {
    name: "man-hpdjqahehr3xz9zk.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "23",
  },
  {
    name: "man-hrg80favzhfaatbf.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "70",
  },
  {
    name: "man-hyt0tq6bx8x1emh1.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "37",
  },
  {
    name: "man-i0vvjdieh5oy35gw.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "26",
  },
  {
    name: "man-iidh5uoy56sovnmy.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "54",
  },
  {
    name: "man-ilurvk2azn3laweo.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "87",
  },
  {
    name: "man-j5zmy260fjlvvn5b.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "100",
  },
  {
    name: "man-jhvu31f61pw3xc9x.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "42",
  },
  {
    name: "man-ju55wu5ybx4vffv3.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "61",
  },
  {
    name: "man-k2kz2zzck5aw0zsn.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "80",
  },
  {
    name: "man-kbes4d6yx7elnowy.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "95",
  },
  {
    name: "man-l81eksln8nkq1oc0.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "57",
  },
  {
    name: "man-lexef4lb4yi61kc1.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "52",
  },
  {
    name: "man-lkm6iyhc8dstiqcf.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "88",
  },
  {
    name: "man-lw8ujy12up8o8gel.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "92",
  },
  {
    name: "man-lyudeoxxrswf316w.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "45",
  },
  {
    name: "man-mekmv8ruz0n2cdd3.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "15",
  },
  {
    name: "man-mepevhi1cstepqv6.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "68",
  },
  {
    name: "man-mexf1a1rumgalusm.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "94",
  },
  {
    name: "man-mzldi6aa9vqradoe.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "47",
  },
  {
    name: "man-nbh3e2nscq4p3i9f.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "55",
  },
  {
    name: "man-nf1uup3hly9cps2q.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "82",
  },
  {
    name: "man-njoob83sr83mrltn.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "33",
  },
  {
    name: "man-nrxtijdyd2k6fr4r.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "17",
  },
  {
    name: "man-o3q39bgsrz9miq3o.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "85",
  },
  {
    name: "man-p723eam40dtk90jr.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "44",
  },
  {
    name: "man-pw912x2yufsi6zbv.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "51",
  },
  {
    name: "man-qrog0gtv722xpl7r.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "74",
  },
  {
    name: "man-qst3hnw4nu824u6n.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "67",
  },
  {
    name: "man-quco9njcst8jeuhy.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "35",
  },
  {
    name: "man-r32mqy64c6m3fgrg.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "28",
  },
  {
    name: "man-r7sanlwn6u8pjj0v.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "81",
  },
  {
    name: "man-riyvomsudgjv94et.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "27",
  },
  {
    name: "man-s5m1p6718xhk6hm5.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "72",
  },
  {
    name: "man-sb5dxqrz554vxyvj.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "75",
  },
  {
    name: "man-suo9pw43cqol3mhe.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "20",
  },
  {
    name: "man-t1tsdlelkan0j8rt.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "86",
  },
  {
    name: "man-t4sqhfnqwa7r8bwv.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "14",
  },
  {
    name: "man-tjw6tz0b41kaukwy.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "10",
  },
  {
    name: "man-tmb3oa594jr48b1f.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "71",
  },
  {
    name: "man-u6y0xzd6r9khfwed.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "50",
  },
  {
    name: "man-ueq397a59xbnw0xr.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "59",
  },
  {
    name: "man-uhr82i09cskp48sb.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "8",
  },
  {
    name: "man-ujgpqfxh652ljlc5.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "22",
  },
  {
    name: "man-utd35p3ac23i0g3m.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "46",
  },
  {
    name: "man-v3u2thdpdiaezw2z.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "93",
  },
  {
    name: "man-v60ozzyaud9eer3f.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "4",
  },
  {
    name: "man-v73z57gh2kdhg3mt.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "16",
  },
  {
    name: "man-vbt9hf9wsm9hoag8.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "89",
  },
  {
    name: "man-vhwi7g5p4ovqk9nq.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "1",
  },
  {
    name: "man-vrnh0oxt78ftvujp.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "78",
  },
  {
    name: "man-xky52mditxtviogw.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "63",
  },
  {
    name: "man-xv0t95db2e2ltbr1.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "97",
  },
  {
    name: "man-xxs7fjgda0g03qvo.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "12",
  },
  {
    name: "man-y3fjikuwdfa2xpqy.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "48",
  },
  {
    name: "man-y4datsqgko2pfuek.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "31",
  },
  {
    name: "man-y87pa4ui62a9iwem.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "39",
  },
  {
    name: "man-y9sgzaw1rudp3hgz.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "91",
  },
  {
    name: "man-zqj16qsdfmk0mxm6.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "76",
  },
  {
    name: "sas-13r98sg655nf3fnl.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "30",
  },
  {
    name: "sas-1jisc6y0cwoovty9.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "93",
  },
  {
    name: "sas-1mrrl97er1bhn921.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "89",
  },
  {
    name: "sas-1ofyz76zotc7rf5j.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "91",
  },
  {
    name: "sas-21vy6hbpij3gkw68.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "72",
  },
  {
    name: "sas-2594gb8uuz3v1x16.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "17",
  },
  {
    name: "sas-2mdrak4owoyut8wa.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "11",
  },
  {
    name: "sas-2ogblby4wc9azdpd.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "65",
  },
  {
    name: "sas-30erkw0wg2fm5f5b.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "8",
  },
  {
    name: "sas-3fczgipitzs96r0t.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "69",
  },
  {
    name: "sas-3kg3ugh9l8fc2bau.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "62",
  },
  {
    name: "sas-3o98fhi7a107g7r9.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "44",
  },
  {
    name: "sas-473taethi92viwvo.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "12",
  },
  {
    name: "sas-4ddgrkbifmeso9d1.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "71",
  },
  {
    name: "sas-4hpwhrv44o82neth.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "50",
  },
  {
    name: "sas-4ic1t7mix7ptbkr3.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "47",
  },
  {
    name: "sas-4seqoorh7saqiuwn.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "6",
  },
  {
    name: "sas-5botfi9b8jmnvrv0.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "46",
  },
  {
    name: "sas-5d5sffjh4vviu2l3.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "99",
  },
  {
    name: "sas-5y6zjy8ubu9t6pu0.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "67",
  },
  {
    name: "sas-6bjmh4i0swdayv01.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "90",
  },
  {
    name: "sas-6bqpmxgwwzrspr2c.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "40",
  },
  {
    name: "sas-6n0f8egkl1qn2rn8.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "33",
  },
  {
    name: "sas-6r1mbhn6jqp4kahn.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "82",
  },
  {
    name: "sas-756x7igpnxp25l9b.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "59",
  },
  {
    name: "sas-78y3pbygwxm2xlwp.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "85",
  },
  {
    name: "sas-79dwa3xrma1sjt8q.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "31",
  },
  {
    name: "sas-79uohffi3mrpc0by.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "83",
  },
  {
    name: "sas-8bxof4pdlqcluyz2.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "27",
  },
  {
    name: "sas-8feqhora8khytk5a.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "60",
  },
  {
    name: "sas-8re22l99cgytejrr.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "38",
  },
  {
    name: "sas-982v3vr0fbm1n7vy.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "4",
  },
  {
    name: "sas-9r5danajyn2v2pzw.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "49",
  },
  {
    name: "sas-9teqlwphxd1gqh4k.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "23",
  },
  {
    name: "sas-9w5i3bz3ion3irf0.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "63",
  },
  {
    name: "sas-adq558u10wnb5f91.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "84",
  },
  {
    name: "sas-asewe3ucaze98e0m.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "9",
  },
  {
    name: "sas-be8vdi09ouppuwbk.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "70",
  },
  {
    name: "sas-bigid7wjaip48wt0.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "73",
  },
  {
    name: "sas-c08nr6avbvrdf6k3.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "10",
  },
  {
    name: "sas-c30775qc3f6xksqq.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "80",
  },
  {
    name: "sas-ciooxvb8su5dbr51.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "56",
  },
  {
    name: "sas-dclerum3hpsbkm6b.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "25",
  },
  {
    name: "sas-ddz79celsmtlukol.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "3",
  },
  {
    name: "sas-du6w6oy8nusysv4j.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "1",
  },
  {
    name: "sas-e0a22nzp2ot2p2zf.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "41",
  },
  {
    name: "sas-e96nnuav6lt754uk.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "39",
  },
  {
    name: "sas-eweoz8qpi7ztmpmt.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "16",
  },
  {
    name: "sas-fjc3h8tr9tz4vbyu.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "87",
  },
  {
    name: "sas-fqlooh9cuqarbdgx.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "94",
  },
  {
    name: "sas-g6hufvpbp7a155bj.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "24",
  },
  {
    name: "sas-gf0l336xnxp0486r.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "43",
  },
  {
    name: "sas-gk126hvpf1xd78k9.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "88",
  },
  {
    name: "sas-gk3vyxborw7w4b3m.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "32",
  },
  {
    name: "sas-gpxzyxvgqz5dkhrk.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "22",
  },
  {
    name: "sas-how01u92el4nxgwd.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "13",
  },
  {
    name: "sas-hxbhk4lh28fgsmvz.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "96",
  },
  {
    name: "sas-i0zkn52ddsq1urww.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "98",
  },
  {
    name: "sas-i4rqj4l6n1lm6965.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "48",
  },
  {
    name: "sas-ix7pqh7tg9lehde5.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "36",
  },
  {
    name: "sas-jghk5z1slsi92126.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "20",
  },
  {
    name: "sas-joczn2p5gctz3e5m.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "51",
  },
  {
    name: "sas-kyiozl76q3tcyd5w.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "28",
  },
  {
    name: "sas-l2orwufticvwk2xy.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "61",
  },
  {
    name: "sas-lvodc4kyswfs4rah.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "19",
  },
  {
    name: "sas-morzz7ubhlh3ue3e.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "45",
  },
  {
    name: "sas-mw5tpfunptvj8imw.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "14",
  },
  {
    name: "sas-n2sqt2tp3ibbcwqv.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "77",
  },
  {
    name: "sas-ntrhmnppfj4fpxdw.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "54",
  },
  {
    name: "sas-o5ixa1ik0c9kk5y8.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "37",
  },
  {
    name: "sas-o6xdwzh6wrmm2bgy.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "58",
  },
  {
    name: "sas-o8x35yc3e28mqkm9.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "100",
  },
  {
    name: "sas-olwktnl0jyiketwx.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "66",
  },
  {
    name: "sas-oq8df3gpcbinew2y.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "78",
  },
  {
    name: "sas-ov9tc0gzaoeb6gwa.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "81",
  },
  {
    name: "sas-pbdksdho50ama9po.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "15",
  },
  {
    name: "sas-psg7pr7t261b3hmk.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "18",
  },
  {
    name: "sas-q05wlcnfkk33kqdq.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "35",
  },
  {
    name: "sas-q1se66vr9hiwogf9.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "68",
  },
  {
    name: "sas-q2obgb2lyvut76ke.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "55",
  },
  {
    name: "sas-q5dh018c49aja41r.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "5",
  },
  {
    name: "sas-qnry2nn5qatd8hv9.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "95",
  },
  {
    name: "sas-r0lngs7jhuxj8uk7.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "92",
  },
  {
    name: "sas-s1ipmopboyxt2kln.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "75",
  },
  {
    name: "sas-syjmu3mjlialsd8e.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "97",
  },
  {
    name: "sas-sztw9ivovy2aq0b8.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "26",
  },
  {
    name: "sas-t877cpftfhojkb0o.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "52",
  },
  {
    name: "sas-tcv2iy34z4d0ucpg.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "57",
  },
  {
    name: "sas-txnigp64orh810wt.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "2",
  },
  {
    name: "sas-u87uodw46o4z4zh5.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "53",
  },
  {
    name: "sas-ux0x6tom5f3i86c1.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "42",
  },
  {
    name: "sas-va9x1its5emgcxva.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "86",
  },
  {
    name: "sas-vmjsluhp50suorn5.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "64",
  },
  {
    name: "sas-x9rfiag8pi41frgr.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "76",
  },
  {
    name: "sas-xksbc6z8ttcm5nvu.db.yandex.net",
    type: "ZOOKEEPER",
    health: "ALIVE",
  },
  {
    name: "sas-ya4e6oh47j3wa8dl.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "74",
  },
  {
    name: "sas-yf5ytjufoq6xbs8l.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "79",
  },
  {
    name: "sas-yhansqwaorrct2bc.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "21",
  },
  {
    name: "sas-yun642wm9cfhdeer.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "7",
  },
  {
    name: "sas-yyaf6krkmrbbp6ix.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "34",
  },
  {
    name: "sas-ziebtot0ni976oxz.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "29",
  },
  {
    name: "vla-0fy73etftwf54z05.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "80",
  },
  {
    name: "vla-0mcykyrr18w0fduk.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "92",
  },
  {
    name: "vla-0qo82oe8zb4moyok.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "35",
  },
  {
    name: "vla-15ux9dmvjsfoaedr.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "68",
  },
  {
    name: "vla-1btg7mouf86j9e36.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "15",
  },
  {
    name: "vla-1kmxyiop3njlp3pt.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "70",
  },
  {
    name: "vla-2g2k77o8ceb76ere.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "88",
  },
  {
    name: "vla-2mipuijfaed1kcny.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "31",
  },
  {
    name: "vla-38i85pc32x6satf3.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "87",
  },
  {
    name: "vla-3kks04jgk52qbv2j.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "50",
  },
  {
    name: "vla-3p0fhxk4wrjk1lp6.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "1",
  },
  {
    name: "vla-3t5rvd379zoo56fm.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "24",
  },
  {
    name: "vla-4l70eh94v7xnutbc.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "82",
  },
  {
    name: "vla-62umquqsqgjqikpq.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "60",
  },
  {
    name: "vla-7hfyl3x40pse7yea.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "28",
  },
  {
    name: "vla-7q3rsq9vguudxeaa.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "2",
  },
  {
    name: "vla-7uiw3ak3ubemhzjd.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "53",
  },
  {
    name: "vla-8bikiizdmdjhrt74.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "71",
  },
  {
    name: "vla-8k7cz5g26ml7ek19.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "62",
  },
  {
    name: "vla-8t25ewyyopgpnq0h.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "5",
  },
  {
    name: "vla-8z4ptbcbz0b6wluc.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "18",
  },
  {
    name: "vla-9085oxcu5sn8lufx.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "33",
  },
  {
    name: "vla-91iszhaz43s446b5.db.yandex.net",
    type: "ZOOKEEPER",
    health: "ALIVE",
  },
  {
    name: "vla-96jo75kgu3xgqx7p.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "10",
  },
  {
    name: "vla-97d9hdhdq9lrcq3x.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "85",
  },
  {
    name: "vla-9abn4bvus4lujrk5.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "41",
  },
  {
    name: "vla-9x8lhfdpw5l8i249.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "45",
  },
  {
    name: "vla-ap24om84mipusbrc.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "8",
  },
  {
    name: "vla-ayi5uuzdakd39m1y.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "12",
  },
  {
    name: "vla-bonba5viwi8brun1.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "63",
  },
  {
    name: "vla-cbm07xsb9rh19u11.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "93",
  },
  {
    name: "vla-cbmzqlwo44g7vbl1.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "42",
  },
  {
    name: "vla-cve9846vhm5mokb8.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "16",
  },
  {
    name: "vla-d8t1r79nmzsa0xd3.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "14",
  },
  {
    name: "vla-dsy2vyzesjtg6kg1.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "39",
  },
  {
    name: "vla-e35gqsljkx2fpea5.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "61",
  },
  {
    name: "vla-ekdgfwid2az60oxq.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "89",
  },
  {
    name: "vla-elzymayf1cplsxqy.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "29",
  },
  {
    name: "vla-f4n61c38lf63k07k.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "66",
  },
  {
    name: "vla-gfchfif5nq7tzhia.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "6",
  },
  {
    name: "vla-ggvzbjxfedglmqw8.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "27",
  },
  {
    name: "vla-gnrovxrtdk6j30jf.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "98",
  },
  {
    name: "vla-h0wknd52wrmn5q1o.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "72",
  },
  {
    name: "vla-hl0q5vmvjzzmpfyg.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "75",
  },
  {
    name: "vla-ho2k4mklf8t42ze7.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "13",
  },
  {
    name: "vla-hpb95axxyu61d0y5.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "44",
  },
  {
    name: "vla-hpftcmzquyaguw3q.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "7",
  },
  {
    name: "vla-j84mrwrtuzt0bpjs.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "99",
  },
  {
    name: "vla-jd17vfciird5f465.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "20",
  },
  {
    name: "vla-kzomu1ludzdbwue1.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "94",
  },
  {
    name: "vla-l6kymghbgujveij0.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "49",
  },
  {
    name: "vla-l8i9jpl3fzaz14g6.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "48",
  },
  {
    name: "vla-lpvfxrkj5y8sdi8e.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "91",
  },
  {
    name: "vla-m0fdsfcc4rlmxs3h.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "51",
  },
  {
    name: "vla-m66gxx7nyqeujbp0.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "56",
  },
  {
    name: "vla-m8821jf55g3h985s.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "32",
  },
  {
    name: "vla-mbam7kvfcq44bi6s.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "77",
  },
  {
    name: "vla-mgihapt4dfqpsahd.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "17",
  },
  {
    name: "vla-mkswwzqk5d96b3ok.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "26",
  },
  {
    name: "vla-mx4wjsrzzbfujrz7.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "22",
  },
  {
    name: "vla-n0o1jmdms51n5g6n.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "47",
  },
  {
    name: "vla-nlf4blw4jck9smqw.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "34",
  },
  {
    name: "vla-nlxl3q1rrnb4mw1c.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "55",
  },
  {
    name: "vla-nmsrgobz2wq40ep5.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "37",
  },
  {
    name: "vla-nq4cw96xn791vzgq.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "90",
  },
  {
    name: "vla-ogdiby7tjc4kc1s5.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "36",
  },
  {
    name: "vla-onbb2dwnyckshjuf.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "25",
  },
  {
    name: "vla-oo3xifwp86h8uy7j.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "79",
  },
  {
    name: "vla-p02nlxohbr0q1v1x.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "96",
  },
  {
    name: "vla-p28ilrmt3q7c5o07.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "3",
  },
  {
    name: "vla-p41d6kz5fwhyqvhe.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "54",
  },
  {
    name: "vla-p82w2vlerdmuip2t.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "11",
  },
  {
    name: "vla-pkqtzvs23otdw5d7.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "58",
  },
  {
    name: "vla-q22ituh5ryq8oabw.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "97",
  },
  {
    name: "vla-q2716edmtea5cfz6.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "76",
  },
  {
    name: "vla-rccd2claygjha6vd.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "81",
  },
  {
    name: "vla-ruxog9ydexfg2b1y.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "40",
  },
  {
    name: "vla-si1p5ov5yhwxnamr.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "69",
  },
  {
    name: "vla-sknebbdasarbsnws.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "74",
  },
  {
    name: "vla-sz2yg24mclg6mcdo.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "67",
  },
  {
    name: "vla-t8kbq56a979by869.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "57",
  },
  {
    name: "vla-thcceuakgkxaq9ui.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "73",
  },
  {
    name: "vla-u7h1qq1cvurm3i2l.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "9",
  },
  {
    name: "vla-unhejibt8cl94ve2.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "78",
  },
  {
    name: "vla-uq4peuz1e1p4z2eh.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "52",
  },
  {
    name: "vla-v8jgpvrkm9r4tgml.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "65",
  },
  {
    name: "vla-vgjoip8b2h1xcuyg.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "38",
  },
  {
    name: "vla-vtw6aenic3to9q1h.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "95",
  },
  {
    name: "vla-w9sehzrwysh14ykz.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "4",
  },
  {
    name: "vla-w9xtjyrjq6drtncm.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "59",
  },
  {
    name: "vla-x79u36ne1x1h6au3.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "86",
  },
  {
    name: "vla-x7e1m7v61dbzbc8j.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "43",
  },
  {
    name: "vla-xaz3uo61rggmi8y7.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "100",
  },
  {
    name: "vla-xbhgr4eg7ch2p6ge.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "23",
  },
  {
    name: "vla-xcniqg9v4xel4ke1.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "30",
  },
  {
    name: "vla-xp1bmq6jowdeoe9p.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "21",
  },
  {
    name: "vla-xuu9wrjymmkcmh45.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "64",
  },
  {
    name: "vla-yi3ofi51qhb2s4lo.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "46",
  },
  {
    name: "vla-zfjwrcof43etrmie.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "83",
  },
  {
    name: "vla-zqse1vtawp1wllc3.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "84",
  },
  {
    name: "vla-zwffc0l0ih5b233m.db.yandex.net",
    type: "CLICKHOUSE",
    health: "ALIVE",
    shardName: "19",
  },
];
