export default [
  {
    name: "man-2glaul5u7vyuniyl.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    type: "MONGOCFG",
  },
  {
    name: "man-5zj5wx19ijgjeb9v.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs03",
    type: "MONGOD",
  },
  {
    name: "man-65cmuunhi3kkx4n0.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs02",
    type: "MONGOD",
  },
  {
    name: "man-8zujqz6mp286tbpz.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs04",
    type: "MONGOD",
  },
  {
    name: "man-a28bbil7280r6ei9.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs05",
    type: "MONGOD",
  },
  {
    name: "man-a6slaqinkfdj7k6z.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs19",
    type: "MONGOD",
  },
  {
    name: "man-bz36lgr41zig5526.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs16",
    type: "MONGOD",
  },
  {
    name: "man-cv34zdv495hl8sc0.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs12",
    type: "MONGOD",
  },
  {
    name: "man-e4a3c9e3eiqgqdrq.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs14",
    type: "MONGOD",
  },
  {
    name: "man-el7okqqdyr1wjpx1.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs06",
    type: "MONGOD",
  },
  {
    name: "man-ew5zg92yce9vw4lg.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs13",
    type: "MONGOD",
  },
  {
    name: "man-fp4uy0muf5f1ece5.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs17",
    type: "MONGOD",
  },
  {
    name: "man-grzp64afpf2wnlwm.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs15",
    type: "MONGOD",
  },
  {
    name: "man-jey0174pesvjluvg.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs10",
    type: "MONGOD",
  },
  {
    name: "man-m7rv8v7fguk5up56.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs11",
    type: "MONGOD",
  },
  {
    name: "man-nqd5hp0nay5uflrd.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs01",
    type: "MONGOD",
  },
  {
    name: "man-p7qcwp0u22b7cs7x.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs18",
    type: "MONGOD",
  },
  {
    name: "man-qq9q2a9gehydy1e9.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs09",
    type: "MONGOD",
  },
  {
    name: "man-sue6sf74jv30oeqi.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs07",
    type: "MONGOD",
  },
  {
    name: "man-tze0ttp8it67gnfl.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs08",
    type: "MONGOD",
  },
  {
    name: "man-wybeg1tszoruby6p.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs20",
    type: "MONGOD",
  },
  {
    name: "man-yid4aa2fw11x137b.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs21",
    type: "MONGOD",
  },
  {
    name: "sas-288on372wdk6r2b0.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs11",
    type: "MONGOD",
  },
  {
    name: "sas-3se8bgtj1ittou3j.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs08",
    type: "MONGOD",
  },
  {
    name: "sas-3xynto0tuvr6pb1p.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    type: "MONGOCFG",
  },
  {
    name: "sas-4wq9wmq0jolkdopa.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs18",
    type: "MONGOD",
  },
  {
    name: "sas-5h1l82qtkfejiut1.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs14",
    type: "MONGOD",
  },
  {
    name: "sas-7960x4rb23dosdla.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs12",
    type: "MONGOD",
  },
  {
    name: "sas-7ygvmd6olb5jj82a.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs09",
    type: "MONGOD",
  },
  {
    name: "sas-94mem6wjy4db6huq.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs13",
    type: "MONGOD",
  },
  {
    name: "sas-9sn4hgby4d82qbj7.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs01",
    type: "MONGOD",
  },
  {
    name: "sas-cj96p8qedouepybe.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs06",
    type: "MONGOD",
  },
  {
    name: "sas-cvjjslv0znhihapi.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs02",
    type: "MONGOD",
  },
  {
    name: "sas-dk1t68tzf5z40u5y.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs15",
    type: "MONGOD",
  },
  {
    name: "sas-ec2azofk7fhb8t1e.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs03",
    type: "MONGOD",
  },
  {
    name: "sas-ft9k6rytwuhi8jdj.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs20",
    type: "MONGOD",
  },
  {
    name: "sas-imalnkq3zwvcyxl7.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs19",
    type: "MONGOD",
  },
  {
    name: "sas-ldeo003petd0bpjl.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs04",
    type: "MONGOD",
  },
  {
    name: "sas-ngc0zbfp93a6ycg4.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs07",
    type: "MONGOD",
  },
  {
    name: "sas-rn3tf2zligjqg3ho.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs16",
    type: "MONGOD",
  },
  {
    name: "sas-s8f8mf75thoh5mt9.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs05",
    type: "MONGOD",
  },
  {
    name: "sas-skrel12y2ebyc797.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    type: "MONGOS",
  },
  {
    name: "sas-v7vsm9pmn71wtl13.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs21",
    type: "MONGOD",
  },
  {
    name: "sas-xancczulszt8tpqs.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs17",
    type: "MONGOD",
  },
  {
    name: "sas-zbmh2pp7ltrkz0r2.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs10",
    type: "MONGOD",
  },
  {
    name: "vla-050h5zvubdu8inro.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs04",
    type: "MONGOD",
  },
  {
    name: "vla-0nupm5e83gvlsi96.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs18",
    type: "MONGOD",
  },
  {
    name: "vla-1klrqzubf5rr928m.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs21",
    type: "MONGOD",
  },
  {
    name: "vla-2q8sr03rxvuyjprf.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs20",
    type: "MONGOD",
  },
  {
    name: "vla-5h1w4vbbwklk3oz6.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs17",
    type: "MONGOD",
  },
  {
    name: "vla-61uz1vxxmsfo538u.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs03",
    type: "MONGOD",
  },
  {
    name: "vla-6vgjbo3g1osba3gg.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs01",
    type: "MONGOD",
  },
  {
    name: "vla-8c1oqvxd1conf829.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs15",
    type: "MONGOD",
  },
  {
    name: "vla-8deu9hn72b188wni.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs11",
    type: "MONGOD",
  },
  {
    name: "vla-8zt61hkrfmowt829.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs02",
    type: "MONGOD",
  },
  {
    name: "vla-g1isjjyop0oidyaa.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs13",
    type: "MONGOD",
  },
  {
    name: "vla-gqs91x93iz0ssa7y.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs07",
    type: "MONGOD",
  },
  {
    name: "vla-i7qviagnpk1ms4s8.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    type: "MONGOCFG",
  },
  {
    name: "vla-jk6no6gxlp9ywv52.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs08",
    type: "MONGOD",
  },
  {
    name: "vla-kpxe88ds5d52bkvq.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs09",
    type: "MONGOD",
  },
  {
    name: "vla-krff5zhountt39b8.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs05",
    type: "MONGOD",
  },
  {
    name: "vla-nu7luaw4yib5gteo.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs14",
    type: "MONGOD",
  },
  {
    name: "vla-nububakg20at8ied.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs12",
    type: "MONGOD",
  },
  {
    name: "vla-ny4scp4h7m2yyik9.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs10",
    type: "MONGOD",
  },
  {
    name: "vla-o5dem7ljje8jxzsv.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    type: "MONGOS",
  },
  {
    name: "vla-oiebeort5l5dh10v.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs06",
    type: "MONGOD",
  },
  {
    name: "vla-vmwc32642s3qxzzx.db.yandex.net",
    role: "SECONDARY",
    health: "ALIVE",
    shardName: "rs19",
    type: "MONGOD",
  },
  {
    name: "vla-wqjj6rtbod7ccyhp.db.yandex.net",
    role: "PRIMARY",
    health: "ALIVE",
    shardName: "rs16",
    type: "MONGOD",
  },
];
